CREATE TABLE [dbo].[Bancos]
(
	[BancoId] BIGINT IDENTITY(1,1) NOT NULL
,	[Codigo] VARCHAR(15) NOT NULL
,	[Nome] VARCHAR(200) NOT NULL
,	[Apelido] VARCHAR(50) NOT NULL
,	[NumeroCnpj] VARCHAR(15) NULL
,	[FlagStatus] BIT NOT NULL
,	[CadastroUsuarioId] BIGINT NOT NULL
,	[CadastroDataHora] DATETIME2 NOT NULL
,	[AtualizacaoUsuarioId] BIGINT NULL
,	[AtualizacaoDataHora] DATETIME2 NULL
,	CONSTRAINT [PK_Bancos] PRIMARY KEY CLUSTERED 
	(
		[BancoId] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
