CREATE TABLE [dbo].[TiposPessoas]
(
	[TipoPessoaId] INT IDENTITY(1,1) NOT NULL 
,	[Nome] VARCHAR(50) NOT NULL
,	[Apelido] VARCHAR(20) NOT NULL
,	[Sigla] VARCHAR(3) NULL
,	[FlagStatus] [bit] NOT NULL
,	[CadastroUsuarioId] BIGINT NOT NULL
,	[CadastroDataHora] DATETIME2 NOT NULL
,	[AtualizacaoUsuarioId] BIGINT NULL
,	[AtualizacaoDataHora] DATETIME2 NULL
,	CONSTRAINT [PK_TiposPessoas] PRIMARY KEY CLUSTERED 
	(
		[TipoPessoaId] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
